trigger:
  batch: true

jobs:
- template: Templates/build-publish-dotnetcore.yml
  parameters:
    name: Build Web App
    project: '**/TodoListWebApp/*.csproj'
    buildConfiguration: Debug
    artifactName: TodoList.WebApp
    vmImage: 'vs2017-win2016'