resources:
- repo: self
phases:
- phase: Compile
  displayName: Build Web App

  condition: succeeded()
  queue:
    name: Hosted VS2017
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.0.3'
    inputs:
      version: 2.0.3


  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(Parameters.RestoreBuildProjects)'


  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '$(Parameters.RestoreBuildProjects)'
      arguments: '--configuration $(BuildConfiguration)'


  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'


  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TodoList.WebApp'
    inputs:
      ArtifactName: TodoList.WebApp



- phase: Phase_2
  displayName: Build Test
  condition: succeeded()
  queue:
    name: Hosted VS2017
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.0.3'
    inputs:
      version: 2.0.3


  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore


  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/TodoListWebApp.[Ts]ests/*.csproj'


  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/TodoListWebApp.[Ts]ests/*.csproj'
      arguments: '--output $(build.artifactstagingdirectory) -f "netcoreapp2.0" -r "win10-x64"'
      zipAfterPublish: false
      modifyOutputPath: false


  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TodoList.WebApp.Tests'
    inputs:
      ArtifactName: TodoListWebApp.Tests


